// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../lib/array/array.js', ['clulib.array'], [], false);
goog.addDependency('../../../../lib/async/Completer.js', ['clulib.async.Completer'], ['goog.asserts'], false);
goog.addDependency('../../../../lib/async/async.js', ['clulib.async'], [], false);
goog.addDependency('../../../../lib/cm/Component.js', ['clulib.cm.Component'], ['clulib.async.Completer', 'goog.ui.Component'], false);
goog.addDependency('../../../../lib/cm/ComponentManager.js', ['clulib.cm.ComponentManager'], ['clulib.cm.NodeTree', 'goog.asserts', 'goog.structs.Map'], false);
goog.addDependency('../../../../lib/cm/ComponentNode.js', ['clulib.cm.ComponentNode'], ['goog.crypt.base64', 'goog.structs.Map'], false);
goog.addDependency('../../../../lib/cm/NodeTree.js', ['clulib.cm.NodeTree'], ['clulib.array', 'clulib.async', 'clulib.cm.ComponentNode', 'clulib.dom', 'goog.dom', 'goog.structs.Map'], false);
goog.addDependency('../../../../lib/dom/dom.js', ['clulib.dom'], ['goog.dom'], false);
goog.addDependency('../../../../lib/sdks/sdks.js', ['clulib.sdks'], ['clulib.async.Completer', 'goog.dom'], false);
goog.addDependency('../../../../lib/ui/ToggleButton.js', ['clulib.ui.ToggleButton', 'clulib.ui.ToggleButton.EventType'], ['clulib.cm.Component', 'goog.dom.classlist', 'goog.events.Event', 'goog.events.EventType'], false);
goog.addDependency('../../../../lib/ui/components.js', ['clulib.ui.components'], ['clulib.ui.ToggleButton'], false);
goog.addDependency('../../../../test/array/array_test.js', ['clulib.arrayTest'], ['clulib.array', 'goog.testing.asserts', 'goog.testing.jsunit'], false);
goog.addDependency('../../../../test/async/async_test.js', ['clulib.asyncTest'], ['clulib.async', 'goog.Promise', 'goog.testing.TestCase', 'goog.testing.asserts', 'goog.testing.jsunit'], false);
