language: node_js
node_js:
  - '6'

cache:
  yarn: true
  directories:
    - ./node_modules

notifications:
  email: false

matrix:
  fast_finish: true

install:
  - yarn install

before_script:
  - yarn compile

script:
  - yarn test