language: node_js
node_js:
  - '6'

cache:
  yarn: true
  directories:
    - ./node_modules

notifications:
  email: true

matrix:
  fast_finish: true

before_install:
  - export TZ=Europe/Berlin

install:
  - yarn install

before_script:
  - yarn lint
  - yarn compile

script:
  - yarn test
